name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install test requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Debug: print python env and repo layout
        run: |
          python -c "import sys,os; print('PYTHON:', sys.version); print('EXEC:', sys.executable); print('CWD:', os.getcwd()); print('LISTROOT:', sorted(os.listdir('.'))); import pprint; pprint.pprint(sys.path)" | tee debug.txt
      - name: Run tests (repo-only)
        run: |
          # Run only tests under the repository's tests folders to avoid collecting
          # unrelated tests from system/site-packages.
          pytest -q search/tests --junitxml=pytest-results.xml | tee pytest.log
      - name: Upload debug artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-debug-artifacts
          path: |
            debug.txt
            pytest.log
            pytest-results.xml
      - name: Print short previews of logs
        run: |
          echo "----- debug.txt (first 200 lines) -----"; head -n 200 debug.txt || true
          echo "----- pytest.log (first 200 lines) -----"; head -n 200 pytest.log || true
