name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install test requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Run tests (repo-only)
        run: |
          # Run only tests under the repository's tests folders to avoid collecting
          # unrelated tests from system/site-packages.
          pytest -q search/tests
